work_dir: ./work_dir/fsd_a_dropout/

# feeder
feeder: feeders.feeder_fsd.Feeder
train_feeder_args:
  data_path: data/fsd/raw_data/train_data.npy
  label_path: data/fsd/raw_data/train_label.npy
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  augmentation: 'conf'

test_feeder_args:
  # data_path: data/fsd/raw_data/test_A_data.npy
  data_path: data/fsd/raw_data/eval_data.npy
  label_path: data/fsd/raw_data/eval_label.npy
  split: test
  window_size: 64
  p_interval: [0.95]
  debug: False

bone: False
motion: False

# processor
phase: eval
save_score: False

# model
model: model.ctrgcn.Model
# weights: ./work_dir/fsd_bmotion/best.pdparams
model_args:
  num_class: 30
  num_point: 25
  num_person: 1
  graph: graph.fsd.Graph
  graph_args:
    labeling_mode: 'spatial'
  drop_out: 0.5

#optim
start_epoch: 0
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
cpu: False
device: []
batch_size: 12
test_batch_size: 8
num_epoch: 70
nesterov: True
